# What a program that uses part of this library actually links.
#
#   powershell -File scripts\check-dependencies.ps1
#   powershell -File scripts\check-dependencies.ps1 -Platform Win32
#
# check-format-isolation.ps1 proves the FORMATS are independent of each
# other. This proves the layers are independent of the frameworks: a console
# program built on Core, or on Core and JSON, links no VCL, no FMX, no
# FireDAC, no Datasnap and no Data.DB - and the DataSet layer, which uses
# FireDAC and Datasnap on purpose, still links no GUI.
#
# The evidence is the linker's own map file, not a grep of uses clauses: a
# dependency three units deep passes a grep and shows up here.

param(
  [ValidateSet('Win32', 'Win64', 'Both')] [string]$Platform = 'Both'
)
$ErrorActionPreference = 'Stop'
$Repo = Split-Path -Parent $PSScriptRoot
$Src  = Join-Path $Repo 'src'
. (Join-Path $PSScriptRoot 'delphi.ps1')
$Ide  = $DelphiBin
$platforms = if ($Platform -eq 'Both') { @('Win32', 'Win64') } else { @($Platform) }
$compilers = @{ 'Win32' = 'dcc32.exe'; 'Win64' = 'dcc64.exe' }

# A GUI FRAMEWORK, not a Windows header: FireDAC links Winapi.CommCtrl on
# Win64, which is an API declaration unit and pulls in no user interface.
$gui = @('Vcl.', 'FMX.')
$db  = @('Data.DB', 'Data.FmtBcd', 'Data.SqlTimSt', 'FireDAC.', 'Datasnap.', 'MidasLib')

# name -> units to use, code to run, prefixes that must NOT be linked
$probes = [ordered]@{
  'CORE_ONLY_BUILD' = @{
    Uses = @('PascalForge.Serialization.Core', 'PascalForge.Serialization')
    Body = "  if TSerialization.IsRegistered(TSerializationFormat.Json) then Halt(1);"
    Forbidden = $gui + $db
  }
  'JSON_CONSOLE_BUILD' = @{
    Uses = @('PascalForge.Serialization.Core', 'PascalForge.Json')
    Body = "  if TJsonSerializer.Serialize<TProbe>(TProbe.Create) = '' then Halt(1);"
    Forbidden = $gui + $db
  }
  'DATASET_ONLY_BUILD' = @{
    Uses = @('PascalForge.Serialization.Core', 'PascalForge.DataSet')
    Body = "  TDataSetSerializer.CreateFDMemTable<TProbe>(TProbe.Create).Free;"
    Forbidden = $gui
  }
}

$work = Join-Path $Repo 'artifacts\dependencies'
if (Test-Path -LiteralPath $work) { Remove-Item -LiteralPath $work -Recurse -Force }
New-Item -ItemType Directory -Force -Path $work | Out-Null

function New-Probe([string]$Name, [hashtable]$P) {
  $uses = @('  System.SysUtils,')
  foreach ($u in $P.Uses) { $uses += "  $u in '$Src\$u.pas'," }
  $uses[-1] = $uses[-1] -replace ',$', ';'
  $src = @"
program $Name;

{ Generated by scripts\check-dependencies.ps1 and rewritten on every run. }

{`$APPTYPE CONSOLE}

uses
$($uses -join "`r`n")

type
  TProbe = class
  public
    Id: Integer;
    Name: string;
  end;

begin
$($P.Body)
  Writeln('$($Name): PASS');
end.
"@
  $path = Join-Path $work "$Name.dpr"
  Set-Content -LiteralPath $path -Value $src -Encoding utf8
  return $path
}

$rows = [System.Collections.Generic.List[object]]::new()
$failed = 0
foreach ($p in $platforms) {
  $exe = Join-Path $Ide $compilers[$p]
  $out = Join-Path $work $p
  New-Item -ItemType Directory -Force -Path $out | Out-Null
  foreach ($name in $probes.Keys) {
    $probe = $probes[$name]
    $dpr = New-Probe -Name $name -P $probe
    $log = Join-Path $out "$name.build.log"
    $args = @(
      '-B', '-Q', '-GD'
      '-NSSystem;System.Win;Winapi;Data;Datasnap;Vcl;Xml;FireDAC'
      "-U$Src", "-NU$out", "-N0$out", "-E$out"
      $dpr
    )
    & $exe @args *> $log
    if ($LASTEXITCODE -ne 0) {
      $rows.Add([pscustomobject]@{ platform = $p; probe = $name; status = 'BUILD_FAIL'; linked = '' })
      $failed++
      continue
    }
    $run = & (Join-Path $out "$name.exe") 2>&1
    $ranOk = ($LASTEXITCODE -eq 0) -and ($run -match "$($name): PASS")
    # Every unit the linker put in the executable, from the detailed map.
    $map = Get-Content -LiteralPath (Join-Path $out "$name.map") -Raw
    $units = @([regex]::Matches($map, 'M=([A-Za-z0-9_\.]+)') |
      ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique)
    $bad = @($units | Where-Object {
      $u = $_
      @($probe.Forbidden | Where-Object { $u.StartsWith($_) }).Count -gt 0
    })
    $ok = $ranOk -and ($units.Count -gt 0) -and ($bad.Count -eq 0)
    if (-not $ok) { $failed++ }
    $rows.Add([pscustomobject]@{
      platform = $p; probe = $name
      status = $(if ($ok) { 'PASS' } elseif (-not $ranOk) { 'RUN_FAIL' } else { 'FORBIDDEN_UNIT' })
      linked = "$($units.Count) units$(if ($bad.Count) { '; forbidden: ' + ($bad -join ', ') })"
    })
  }
}

Write-Host ''
$rows | ForEach-Object { '{0,-6} {1,-20} {2,-15} {3}' -f $_.platform, $_.probe, $_.status, $_.linked }
Write-Host ''
Write-Host "DEPENDENCY_PROBES=$($rows.Count)"
Write-Host "DEPENDENCY_FAILED=$failed"
$core = @($rows | Where-Object { $_.probe -in 'CORE_ONLY_BUILD', 'JSON_CONSOLE_BUILD' -and $_.status -ne 'PASS' }).Count -eq 0
Write-Host ("CONSOLE_CORE_JSON_NO_GUI_DB: {0}" -f $(if ($core) { 'PASS' } else { 'FAIL' }))
if ($failed -eq 0) { Write-Host 'DEPENDENCY_AUDIT: PASS'; exit 0 }
Write-Host 'DEPENDENCY_AUDIT: FAIL'
exit 1
