# Prove that the formats are independent, by building applications that
# contain some of them and not the others.
#
#   powershell -File scripts\check-format-isolation.ps1
#   powershell -File scripts\check-format-isolation.ps1 -Platform Win64
#
# Source scanning can show that no unit NAMES another format. Only a build
# can show that none of them DRAGS one in: a stray uses entry three units
# deep would pass a grep and fail here.
#
# Each probe is a tiny program generated into artifacts\, compiled with src\
# as the only search path, and then read back to confirm that exactly the
# formats it asked for are linked - not fewer, and not more.

param(
  [ValidateSet('Win32', 'Win64', 'Both')] [string]$Platform = 'Both'
)
$ErrorActionPreference = 'Stop'
$Repo = Split-Path -Parent $PSScriptRoot
$Src  = Join-Path $Repo 'src'
. (Join-Path $PSScriptRoot 'delphi.ps1')
$Ide  = $DelphiBin

$platforms = if ($Platform -eq 'Both') { @('Win32', 'Win64') } else { @($Platform) }
$compilers = @{ 'Win32' = 'dcc32.exe'; 'Win64' = 'dcc64.exe' }

# Every format, as the UNIT STEM that implements it and the
# TSerializationFormat values that stem registers. They are not the same
# list: ASN.1 is one schema language with three encoding rules, so one set of
# units registers three enumeration values.
#
# A format joins this file in one place. A stem whose units are not present
# yet is skipped with a reason rather than failing, so this script stays
# useful while formats are still arriving.
$known = [ordered]@{
  'Json'        = @('Json')
  'Xml'         = @('Xml')
  'Bson'        = @('Bson')
  'Protobuf'    = @('Protobuf')
  'Cbor'        = @('Cbor')
  'MessagePack' = @('MessagePack')
  'Yaml'        = @('Yaml')
  'Csv'         = @('Csv')
  'Avro'        = @('Avro')
  'Asn1'        = @('Asn1Ber', 'Asn1Der', 'Asn1Cer')
}

$stems = @($known.Keys | Where-Object {
  Test-Path -LiteralPath (Join-Path $Src "PascalForge.$_.pas")
})
$absent = @($known.Keys | Where-Object { $stems -notcontains $_ })

# One probe per format ALONE — the question that matters, because a format
# that drags a sibling in fails here and nowhere else — plus a few
# combinations and the whole set.
$probes = [ordered]@{}
foreach ($s in $stems) { $probes[($s.ToUpper() + '_ONLY_BUILD')] = @($s) }
if (($stems -contains 'Json') -and ($stems -contains 'Xml'))      { $probes['JSON_XML_BUILD'] = @('Json', 'Xml') }
if (($stems -contains 'Json') -and ($stems -contains 'Bson'))     { $probes['JSON_BSON_BUILD'] = @('Json', 'Bson') }
if (($stems -contains 'Xml')  -and ($stems -contains 'Bson'))     { $probes['XML_BSON_BUILD'] = @('Xml', 'Bson') }
if (($stems -contains 'Json') -and ($stems -contains 'Protobuf')) { $probes['JSON_PROTOBUF_BUILD'] = @('Json', 'Protobuf') }
# CSV may reach JSON through the REGISTRY for its JsonCell strategy. That is
# allowed and is why this pair is probed: the point is that CSV alone must
# still link without JSON, which the CSV_ONLY_BUILD probe above proves.
if (($stems -contains 'Csv')  -and ($stems -contains 'Json'))     { $probes['CSV_JSON_BUILD'] = @('Csv', 'Json') }
$probes['ALL_FORMATS_BUILD'] = $stems

$work = Join-Path $Repo 'artifacts\isolation'
if (Test-Path -LiteralPath $work) { Remove-Item -LiteralPath $work -Recurse -Force }
New-Item -ItemType Directory -Force -Path $work | Out-Null

function New-Probe {
  param([string]$Name, [string[]]$Stems)

  $uses = @(
    "  System.SysUtils,"
    "  PascalForge.Serialization.Core in '$Src\PascalForge.Serialization.Core.pas',"
    "  PascalForge.Serialization in '$Src\PascalForge.Serialization.pas',"
  )
  foreach ($s in $Stems) {
    $uses += "  PascalForge.$s in '$Src\PascalForge.$s.pas',"
    $uses += "  PascalForge.$s.Registration in '$Src\PascalForge.$s.Registration.pas',"
  }
  $uses[-1] = $uses[-1] -replace ',$', ';'

  # The enumeration values this probe expects to be registered, and every
  # other value any present stem could have registered. A format that drags a
  # sibling in shows up as one of the latter turning True.
  $expectedValues = @()
  foreach ($s in $Stems) { $expectedValues += $known[$s] }
  $allValues = @()
  foreach ($s in $stems) { $allValues += $known[$s] }

  $checks = foreach ($v in $allValues) {
    $expected = if ($expectedValues -contains $v) { 'True' } else { 'False' }
    "  if TSerialization.IsRegistered(TSerializationFormat.$v) <> $expected then Wrong('$v');"
  }
  $expectedCount = $expectedValues.Count
  $registers = foreach ($s in $Stems) { "  T$($s)SerializationRegistration.RegisterFormat;" }

  $src = @"
program $Name;

{ Generated by scripts\check-format-isolation.ps1. Do not edit: it is
  rewritten on every run. }

{`$APPTYPE CONSOLE}

uses
$($uses -join "`r`n")

var
  GBad: Integer = 0;

procedure Wrong(const AFormat: string);
begin
  Writeln('  ', AFormat, ' is linked when it should not be, or missing when ',
    'it should be');
  Inc(GBad);
end;

begin
  { Linking registered nothing: registration is explicit. }
  if Length(TSerialization.RegisteredFormats) <> 0 then
  begin
    Writeln('  a format registered itself because it was linked');
    Inc(GBad);
  end;
$($registers -join "`r`n")
$($checks -join "`r`n")
  { Exactly the formats this probe asked for, and no others. }
  if Length(TSerialization.RegisteredFormats) <> $($expectedCount) then
  begin
    Writeln('  wrong number of registered formats: ',
      Length(TSerialization.RegisteredFormats));
    Inc(GBad);
  end;
  if GBad = 0 then Writeln('$($Name): PASS')
  else
  begin
    Writeln('$($Name): FAIL');
    ExitCode := 1;
  end;
end.
"@
  $path = Join-Path $work "$Name.dpr"
  Set-Content -LiteralPath $path -Value $src -Encoding utf8
  return $path
}

$rows = [System.Collections.Generic.List[object]]::new()
$failed = 0

foreach ($p in $platforms) {
  $exe = Join-Path $Ide $compilers[$p]
  if (-not (Test-Path -LiteralPath $exe)) {
    $rows.Add([pscustomobject]@{ platform = $p; probe = '-'; status = 'NO_COMPILER' })
    continue
  }
  $out = Join-Path $work $p
  New-Item -ItemType Directory -Force -Path $out | Out-Null

  foreach ($name in $probes.Keys) {
    $dpr = New-Probe -Name $name -Stems $probes[$name]
    $log = Join-Path $out "$name.build.log"
    $args = @(
      '-B', '-Q', '-GD'
      '-NSSystem;System.Win;Winapi;Data;Datasnap;Vcl;Xml'
      "-U$Src", "-NU$out", "-N0$out", "-E$out"
      $dpr
    )
    & $exe @args *> $log
    if ($LASTEXITCODE -ne 0) {
      $rows.Add([pscustomobject]@{ platform = $p; probe = $name; status = 'BUILD_FAIL' })
      $failed++
      continue
    }
    $run = & (Join-Path $out "$name.exe") 2>&1
    $ok = ($LASTEXITCODE -eq 0) -and ($run -match "$($name): PASS")
    # Linking registers nothing, so the registry cannot show a sibling that a
    # stray uses entry dragged in; the linker map can. Exactly the formats
    # asked for have their engine in the map, and no others.
    $map = Get-Content -LiteralPath (Join-Path $out "$name.map") -Raw
    foreach ($s in $stems) {
      $inMap = ([string]$map).Contains("M=PascalForge.$s.Internal")
      if ($inMap -ne ($probes[$name] -contains $s)) {
        $ok = $false
        $run = @($run) + "  map: PascalForge.$s.Internal linked=$inMap, expected=$($probes[$name] -contains $s) (map $($map.Length) chars)"
      }
    }
    $rows.Add([pscustomobject]@{
      platform = $p; probe = $name
      status = $(if ($ok) { 'PASS' } else { 'FAIL' })
    })
    if (-not $ok) { $failed++; $run | ForEach-Object { Write-Host "    $_" } }
  }
}

Write-Host ''
$rows | ForEach-Object { '{0,-6} {1,-26} {2}' -f $_.platform, $_.probe, $_.status }
Write-Host ''
# A format whose units are not in src yet is NOT silently ignored: saying
# which ones were skipped is the difference between "everything passes" and
# "everything that exists passes".
if ($absent.Count -gt 0) {
  Write-Host "ISOLATION_SKIPPED_NOT_PRESENT=$($absent -join ',')"
}
Write-Host "ISOLATION_FORMATS=$($stems -join ',')"
Write-Host "ISOLATION_PROBES=$($rows.Count)"
Write-Host "ISOLATION_FAILED=$failed"
Write-Host ''
if ($failed -eq 0) { Write-Host 'FORMAT_BUILD_ISOLATION: PASS'; exit 0 }
Write-Host 'FORMAT_BUILD_ISOLATION: FAIL'
exit 1
